### PR TITLE
Buildversion plugin

### PR DESCRIPTION
**Pull request by marmoure**
adding buildversion-maven-plugin to `pom.xml`

### CODE REVIEW

**Comment by adamretter** [comment]
@marmoure Can you rebase this please on `origin/main` please

**Comment by marmoure** [comment]
how can i see the effect of this plugin?

**Review by adamretter — APPROVED** [review]

**Comment by adamretter** [comment]
@marmoure So this plugin simply sets a bunch of properties. They can then be used in other places in the build, if you check the docs you will see what properties it sets. If you check some of the example POM files I sent you, you will see those properties are then used in the jar, javadoc, sources, plugins

**Comment by marmoure** [comment]
i read the docs for the properties but they didnt specify where i ll be seeing them they only said its similar to ` buildnumber-maven-plugin`
Thanks Adam

**Pull request merged**
